/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: zhenkoest (https://sketchfab.com/zhenko)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/zakopane-corner-of-ruin-building-6a2b4f6c064942f28eb8e82f73588a1c
title: Zakopane, Corner of ruin building.
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Ruin({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF('/models/architecture/ruin/ruin.gltf');
  return (
    <group ref={group} {...props} position={[2, 0, -0.5]} dispose={null}>
      <group position={[-0.06, 1.13, 3.22]} rotation={[3.1, 0.01, 0.03]}>
        <group rotation={[-Math.PI, 0, 0]}>
          <mesh
            geometry={nodes.Stereo_textured_mesh_Material0_0.geometry}
            material={materials.Material0}
          />
          <mesh
            geometry={nodes.Stereo_textured_mesh_Material0_0_1.geometry}
            material={materials.Material0}
          />
          <mesh
            geometry={nodes.Stereo_textured_mesh_Material0_0_2.geometry}
            material={materials.Material0}
          />
          <mesh
            geometry={nodes.Stereo_textured_mesh_Material0_0_3.geometry}
            material={materials.Material0}
          />
          <mesh
            geometry={nodes.Stereo_textured_mesh_Material0_0_4.geometry}
            material={materials.Material0}
          />
          <mesh
            geometry={nodes.Stereo_textured_mesh_Material0_0_5.geometry}
            material={materials.Material0}
          />
          <mesh
            geometry={nodes.Stereo_textured_mesh_Material0_0_6.geometry}
            material={materials.Material0}
          />
          <mesh
            geometry={nodes.Stereo_textured_mesh_Material0_0_7.geometry}
            material={materials.Material0}
          />
          <mesh
            geometry={nodes.Stereo_textured_mesh_Material0_0_8.geometry}
            material={materials.Material0}
          />
          <mesh
            geometry={nodes.Stereo_textured_mesh_Material0_0_9.geometry}
            material={materials.Material0}
          />
          <mesh
            geometry={nodes.Stereo_textured_mesh_Material0_0_10.geometry}
            material={materials.Material0}
          />
          <mesh
            geometry={nodes.Stereo_textured_mesh_Material0_0_11.geometry}
            material={materials.Material0}
          />
          <mesh
            geometry={nodes.Stereo_textured_mesh_Material1_0.geometry}
            material={materials.Material1}
          />
          <mesh
            geometry={nodes.Stereo_textured_mesh_Material1_0_1.geometry}
            material={materials.Material1}
          />
          <mesh
            geometry={nodes.Stereo_textured_mesh_Material1_0_2.geometry}
            material={materials.Material1}
          />
          <mesh
            geometry={nodes.Stereo_textured_mesh_Material1_0_3.geometry}
            material={materials.Material1}
          />
          <mesh
            geometry={nodes.Stereo_textured_mesh_Material1_0_4.geometry}
            material={materials.Material1}
          />
          <mesh
            geometry={nodes.Stereo_textured_mesh_Material1_0_5.geometry}
            material={materials.Material1}
          />
          <mesh
            geometry={nodes.Stereo_textured_mesh_Material1_0_6.geometry}
            material={materials.Material1}
          />
          <mesh
            geometry={nodes.Stereo_textured_mesh_Material1_0_7.geometry}
            material={materials.Material1}
          />
          <mesh
            geometry={nodes.Stereo_textured_mesh_Material1_0_8.geometry}
            material={materials.Material1}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/ruin.gltf');
