/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Korpusenko (https://sketchfab.com/Korpusenko)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/mira-573a125189704a7685389ca6a13d7350
title: Mira
*/

import React, { useEffect, useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export default function Human({ ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('/models/human/human.gltf');
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    console.log(actions);
    actions['Take 001'].play();
  }, []);
  return (
    <group
      ref={group}
      {...props}
      scale={0.007}
      position={[0, 0, 5]}
      dispose={null}
    >
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="db04a86ef8df4061b2a6729b077ed511fbx"
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <primitive object={nodes._rootJoint} />
                  <group name="Object_6" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="Mira" rotation={[-Math.PI / 2, 0, 0]} />
                  <skinnedMesh
                    name="Object_7"
                    geometry={nodes.Object_7.geometry}
                    material={materials['24_-_Default']}
                    skeleton={nodes.Object_7.skeleton}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/human.gltf');
