/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Benjamin Gallegos (https://sketchfab.com/artygalop)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/robot-explorer-7dd41219050c437eadfd5d9caad9031b
title: Robot Explorer
*/

import React, { useEffect, useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('/models/robot/robot.gltf');
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    console.log(actions);
    actions['idle'].play();
  }, []);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          position={[-0.01, -315.58, -18.65]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <group
            name="d1148a0122b1411a84b9aed0e3f1b4c4fbx"
            rotation={[-Math.PI, 0, 0]}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group name="robot_grp" rotation={[Math.PI / 2, 0, 0]}>
                  <group name="model_grp">
                    <group name="robot" />
                  </group>
                  <group name="skeleton_grp">
                    <group name="Object_8">
                      <primitive object={nodes._rootJoint} />
                      <group name="Object_10" rotation={[Math.PI / 2, 0, 0]} />
                      <skinnedMesh
                        name="Object_11"
                        geometry={nodes.Object_11.geometry}
                        material={materials.robot_txt02}
                        skeleton={nodes.Object_11.skeleton}
                      />
                      <skinnedMesh
                        name="Object_12"
                        geometry={nodes.Object_12.geometry}
                        material={materials.robot_txt02}
                        skeleton={nodes.Object_12.skeleton}
                      />
                      <skinnedMesh
                        name="Object_13"
                        geometry={nodes.Object_13.geometry}
                        material={materials.robot_txt01}
                        skeleton={nodes.Object_13.skeleton}
                      />
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/robot.gltf');
